# Generated by Django 6.1.1 on 2026-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('possui_cadastur', models.BooleanField(default=False)),
                ('numero_cadastur', models.CharField(blank=True, max_length=50)),
                ('zona', models.CharField(choices=[('urbana', 'Zona Urbana'), ('rural', 'Comunidade Rural')], max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro_comunidade', models.CharField(max_length=150)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('outras_redes', models.URLField(blank=True)),
                ('descricao', models.TextField()),
                ('historia', models.TextField(blank=True)),
                ('dias_funcionamento', models.CharField(blank=True, max_length=255)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255)),
                ('atende_agendamento', models.BooleanField(default=False)),
                ('valoriza_cultura_local', models.BooleanField(default=False)),
                ('como_valoriza_cultura', models.TextField(blank=True)),
                ('sustentabilidade', models.TextField(blank=True)),
                ('acessibilidade', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
