# Generated by Django 6.1.1 on 2026-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('restaurante', 'Restaurante'), ('lanchonete', 'Lanchonete'), ('bar', 'Bar'), ('hotel', 'Hotel'), ('pousada', 'Pousada'), ('hospedagem', 'Hospedagem'), ('artesanato', 'Artesanato'), ('produtor_cultural', 'Produtor Cultural'), ('guia', 'Guia / Condutor Local'), ('comercio', 'Comércio voltado ao Turismo'), ('mototaxi', 'Mototáxi'), ('taxista', 'Taxista'), ('agencia_turismo', 'Agência de Turismo'), ('gastronomia', 'Gastronomia'), ('turismo_rural', 'Turismo Rural'), ('turismo_aventura', 'Turismo de Aventura'), ('atrativo_natural', 'Atrativo Natural'), ('atrativo_cultural', 'Atrativo Cultural'), ('atrativo_religioso', 'Atrativo Religioso'), ('evento', 'Evento'), ('outro', 'Outro')], default='', max_length=50),
        ),
    ]
