# Generated by Django 6.1.1 on 2026-09-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_empreendimento_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='empreendimentos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastro.empreendimento')),
            ],
        ),
    ]
