# Generated by Django 6.1.1 on 2026-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_fotoempreendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='empreendimentos', to='cadastro.categoria'),
        ),
    ]
