# Generated by Django 6.1.1 on 2026-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_categoria_remove_empreendimento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='outras_redes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
