# Generated by Django 6.1.1 on 2026-09-19 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_empreendimento_facebook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='autoriza_divulgacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='cafe_incluso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='deseja_selo_turismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='numero_leitos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='numero_quartos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='possui_caf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='possui_estacionamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='possui_garagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='possui_sicab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='praticas_sustentabilidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreendimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='quarto_acessibilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='tipo_empreendimento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='valor_diarias',
            field=models.TextField(blank=True),
        ),
    ]
